name: 'Build Alpine ISO'
description: 'Creates a bootable Alpine Linux ISO with extra packages'
inputs:
  alpine-version:
    description: 'Alpine version (e.g., 3.19)'
    required: true
  use-cache:
    description: 'Use cached minirootfs if available'
    required: false
    default: 'true'
  build-iso:
    description: 'Whether to build ISO at the end'
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - run: chmod +x scripts/entrypoint.sh
      shell: bash
    - run: ./scripts/entrypoint.sh "${{ inputs.alpine-version }}" "${{ inputs.use-cache }}" "${{ inputs.build-iso }}"
      shell: bash

