name: Build Alpine ISO

on:
  workflow_dispatch:
    inputs:
      alpine_version:
        description: 'Alpine version'
        required: false
        default: '3.20'
      use_cache:
        description: 'Use cache'
        required: false
        default: 'true'
      build_iso:
        description: 'Build ISO'
        required: false
        default: 'true'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y wget p7zip-full xorriso tar bash proot curl squashfs-tools p7zip-full wget

      - name: Make entrypoint executable
        run: chmod +x "${{ github.workspace }}/.github/actions/build-alpine/entrypoint.sh"

      - name: Run Alpine ISO build script
        run: |
          "${{ github.workspace }}/.github/actions/build-alpine/entrypoint.sh" \
            "${{ github.event.inputs.alpine_version }}" \
            "${{ github.event.inputs.use_cache }}" \
            "${{ github.event.inputs.build_iso }}"
