name: Build Alpine ISO

on:
  workflow_dispatch:
    inputs:
      alpine_version:
        description: 'Alpine version'
        required: true
        default: '3.20'
      use_cache:
        description: 'Use cache'
        required: false
        default: 'true'
      build_iso:
        description: 'Build ISO'
        required: false
        default: 'true'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y wget p7zip-full xorriso tar bash proot curl squashfs-tools

      - name: Generate dynamic ISO name
        id: iso
        run: |
          DATE=$(date +"%Y-%m-%d_%H-%M")
          VERSION="${{ github.event.inputs.alpine_version }}"
          ISO_NAME="${DATE}_alpine-${VERSION}-cli-live.iso"
          echo "ISO_NAME=$ISO_NAME" >> $GITHUB_ENV
          echo "iso_name=$ISO_NAME" >> $GITHUB_OUTPUT

      - name: Make entrypoint executable
        run: chmod +x "${{ github.workspace }}/.github/actions/build-alpine/entrypoint.sh"

      - name: Run Alpine ISO build script
        run: |
          "${{ github.workspace }}/.github/actions/build-alpine/entrypoint.sh" \
            "${{ github.event.inputs.alpine_version }}" \
            "${{ github.event.inputs.use_cache }}" \
            "${{ github.event.inputs.build_iso }}" \
            "${{ steps.iso_name.outputs.ISO_NAME }}"

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: alpine-iso
          path: ./iso/${{ env.ISO_NAME }}
