name: Alpine live

on:
  workflow_dispatch:
    inputs:
      alpine-version:
        description: 'Alpine version (e.g. 3.19)'
        required: true
        default: '3.19'
      use-cache:
        description: 'Use cached minirootfs'
        required: false
        default: 'true'
      build-iso:
        description: 'Build the ISO image'
        required: false
        default: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Alpine Live ISO
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: sudo apt-get update && sudo apt-get install -y curl xorriso squashfs-tools proot syslinux

      - name: Build ISO
        uses: ./.github/actions/build-alpine
        with:
          alpine-version: ${{ inputs.alpine-version }}
          use-cache: ${{ inputs.use-cache }}
          build-iso: ${{ inputs.build-iso }}
