name: Build Ubuntu CLI Live ISO

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install -y \
            debootstrap \
            grub-pc-bin \
            grub-efi-amd64-bin \
            grub2-common \
            xorriso \
            mtools \
            squashfs-tools \
            isolinux \
            syslinux-common \
            dosfstools \
            gdisk

      - name: Create working directories
        run: |
          sudo mkdir -p iso/{boot/grub,live}
          sudo mkdir -p chroot

      - name: Bootstrap Ubuntu CLI system
        run: |
          sudo debootstrap --arch=amd64 noble chroot http://archive.ubuntu.com/ubuntu/

      - name: Configure chroot
        run: |
          sudo cp /etc/resolv.conf chroot/etc/
          echo "ubuntu-cli" | sudo tee chroot/etc/hostname
          echo "127.0.0.1 localhost" | sudo tee -a chroot/etc/hosts
          echo "127.0.1.1 ubuntu-cli" | sudo tee -a chroot/etc/hosts

          sudo mount --bind /dev chroot/dev
          sudo mount --bind /proc chroot/proc
          sudo mount --bind /sys chroot/sys

          sudo chroot chroot /bin/bash -c "
            export DEBIAN_FRONTEND=noninteractive

            apt update
            apt install -y \
              linux-image-generic \
              systemd-sysv \
              sudo \
              apparmor \
              live-boot

            useradd -m -s /bin/bash ubuntu
            echo 'ubuntu:ubuntu' | chpasswd
            usermod -aG sudo ubuntu
            echo 'ubuntu ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers.d/ubuntu

            apt clean
          "

          sudo umount chroot/dev
          sudo umount chroot/proc
          sudo umount chroot/sys

      - name: Copy kernel and initrd
        run: |
          sudo cp chroot/boot/vmlinuz-* iso/boot/vmlinuz
          sudo cp chroot/boot/initrd.img-* iso/boot/initrd

      - name: Create squashfs
        run: |
          sudo mksquashfs chroot iso/live/filesystem.squashfs -e boot

      - name: Create GRUB config
        run: |
          cat <<EOF | sudo tee iso/boot/grub/grub.cfg
          set default=0
          set timeout=5

          menuentry "Ubuntu CLI Live" {
              linux /boot/vmlinuz boot=live quiet init=/lib/systemd/systemd
              initrd /boot/initrd
          }
          EOF

      - name: Build ISO
        run: |
          sudo grub-mkrescue -o ubuntu-cli-live.iso iso

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-cli-live
          path: ubuntu-cli-live.iso
