name: Build Alpine Linux Live CLI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-alpine-live:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ISO build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xorriso grub-pc-bin grub-efi-amd64-bin mtools isolinux

      - name: Cache Alpine minirootfs
        uses: actions/cache@v4
        id: cache-alpine
        with:
          path: alpine-minirootfs.tar.gz
          key: alpine-minirootfs-${{ inputs.alpine-version || '3.19' }}-x86_64
          restore-keys: |
            alpine-minirootfs-${{ inputs.alpine-version || '3.19' }}-

      - name: Build Alpine Linux Live CLI
        uses: ./
        with:
          alpine-version: '3.19'
          upload-artifacts: 'true'
          use-cache: 'true'

      - name: Create Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            alpine-live-cli.iso
            alpine-live-cli.iso.sha256
            alpine-live-cli.iso.md5
          body: |
            ## Alpine Linux Live CLI

            Bootowalna dystrybucja Alpine Linux z narzędziami CLI

            ### Zawiera:
            - Python 3.12 z psutil (PySide6 opcjonalnie)
            - Edytory: vim, neovim, nano, mc
            - Narzędzia dyskowe: dd, lsblk, parted, gdisk
            - Kompresja: gzip, zstd, bzip2, xz
            - Bezpieczeństwo: gpg, sha256sum, md5sum
            - Wsparcie UEFI i Legacy BIOS

            ### Użycie:
            1. Pobierz plik ISO
            2. Nagraj na USB/DVD
            3. Bootuj z UEFI lub BIOS
            4. Zaloguj się jako `alpine` (hasło: `alpine`)
        draft: false
        prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
