# .github/workflows/build-simple-ubuntu-live.yml
name: Build Simple Ubuntu Live ISO

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install live-build
      run: |
        sudo apt update
        sudo apt install -y live-build syslinux syslinux-utils isolinux
    
    - name: Create basic live system
      run: |
        mkdir live
        cd live
        
        # Minimalna konfiguracja która na pewno działa
        sudo lb config \
          --distribution jammy \
          --archive-areas "main universe" \
          --mode ubuntu \
          --system live \
          --binary-images iso \
          --bootloader syslinux \
          --debian-installer false
    
    - name: Add your packages
      run: |
        cd live
        cat > config/package-lists/custom.list.chroot << 'EOF'
        curl
        wget
        git
        vim
        htop
        mc
        gparted
        testdisk
        clonezilla
        openssh-client
        net-tools
        python3
        firefox
        EOF
    
    - name: Build ISO
      run: |
        cd live
        sudo lb build
    
    - name: Upload ISO
      run: |
        cd live
        ISO=$(find . -name "*.iso" | head -1)
        if [ -n "$ISO" ]; then
          echo "Found: $ISO"
          ls -lh "$ISO"
          cp "$ISO" ../ubuntu-live-$(date +%Y%m%d).iso
        else
          echo "No ISO found!"
          exit 1
        fi
    
    - name: Save artifact
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-live
        path: "*.iso"
