name: Build Ubuntu 24.04 Live ISO with KDE

on:
  workflow_dispatch:

jobs:
  build-live-iso:
    runs-on: ubuntu-latest
    container: ubuntu:24.04

    steps:
      - name: Install required tools
        run: |
          apt update
          DEBIAN_FRONTEND=noninteractive apt install -y \
            debootstrap \
            xorriso \
            squashfs-tools \
            grub-pc-bin \
            grub-efi-amd64-bin \
            mtools \
            dosfstools \
            isolinux \
            syslinux-utils \
            wget \
            sudo \
            rsync \
            systemd-sysv

      - name: Create working directories
        run: |
          mkdir -p ~/live-build/{chroot,iso}

      - name: Bootstrap Ubuntu 24.04 (noble)
        run: |
          debootstrap --arch=amd64 noble ~/live-build/chroot http://archive.ubuntu.com/ubuntu/

      - name: Configure chroot (KDE + live user)
        run: |
          echo '#!/bin/bash

          export DEBIAN_FRONTEND=noninteractive

          apt update
          apt install -y \
            ubuntu-standard \
            casper \
            network-manager \
            sudo \
            kde-plasma-desktop \
            sddm \
            xinit

          # Create live user
          useradd -m -s /bin/bash liveuser
          echo "liveuser:live" | chpasswd
          usermod -aG sudo liveuser

          # Auto-login
          mkdir -p /etc/sddm.conf.d
          echo "[Autologin]
          User=liveuser
          Session=plasma.desktop" > /etc/sddm.conf.d/autologin.conf

          systemctl enable sddm

          apt clean
          ' > ~/live-build/chroot/customize.sh

          chmod +x ~/live-build/chroot/customize.sh
          mount --bind /dev ~/live-build/chroot/dev
          chroot ~/live-build/chroot /customize.sh
          umount ~/live-build/chroot/dev
          rm ~/live-build/chroot/customize.sh

      - name: Prepare ISO structure
        run: |
          mkdir -p ~/live-build/iso/{casper,boot/grub,isolinux}

          cp /usr/lib/ISOLINUX/isolinux.bin ~/live-build/iso/isolinux/
          cp /usr/lib/syslinux/modules/bios/* ~/live-build/iso/isolinux/

          mksquashfs ~/live-build/chroot ~/live-build/iso/casper/filesystem.squashfs -e boot

          echo "ubuntu 24.04 live" > ~/live-build/iso/README.diskdefines
          echo "casper" > ~/live-build/iso/casper/ubuntu.version

          touch ~/live-build/iso/casper/filesystem.manifest
          touch ~/live-build/iso/casper/filesystem.size

      - name: Copy kernel and initrd
        run: |
          cp ~/live-build/chroot/boot/vmlinuz-* ~/live-build/iso/casper/vmlinuz
          cp ~/live-build/chroot/boot/initrd.img-* ~/live-build/iso/casper/initrd

      - name: Generate GRUB config
        run: |
          cat > ~/live-build/iso/boot/grub/grub.cfg <<EOF
          set timeout=5
          menuentry "Ubuntu 24.04 Live KDE" {
              linux /casper/vmlinuz boot=casper quiet splash ---
              initrd /casper/initrd
          }
          EOF

      - name: Create the ISO
        run: |
          grub-mkrescue -o ~/ubuntu-24.04-live-kde.iso ~/live-build/iso

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-24.04-live-kde
          path: ~/ubuntu-24.04-live-kde.iso
