name: Build Ubuntu 24.04 Live ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Custom Ubuntu ISO

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install -y \
            debootstrap squashfs-tools xorriso isolinux syslinux-utils grub-pc-bin grub-efi-amd64-bin mtools

      - name: Create working directories
        run: |
          mkdir -p iso/{boot/grub,casper}
          mkdir -p custom-image/chroot

      - name: Bootstrap Ubuntu base system
        run: |
          sudo debootstrap --arch=amd64 noble custom-image/chroot http://archive.ubuntu.com/ubuntu

      - name: Chroot and customize the system
        run: |
          sudo cp /etc/resolv.conf custom-image/chroot/etc/
          sudo mount --bind /dev custom-image/chroot/dev
          sudo mount --bind /run custom-image/chroot/run
          sudo chroot custom-image/chroot /bin/bash -c "
            apt update
            apt install -y ubuntu-mate-desktop casper lupin-casper network-manager resolvconf systemd-sysv
            useradd -m -s /bin/bash live
            echo 'live:live' | chpasswd
            echo 'live ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/live
            chmod 0440 /etc/sudoers.d/live
            apt clean
            exit
          "
          sudo umount custom-image/chroot/dev
          sudo umount custom-image/chroot/run

      - name: Create SquashFS image
        run: |
          sudo mksquashfs custom-image/chroot iso/casper/filesystem.squashfs -e boot

      - name: Copy kernel and initrd
        run: |
          sudo cp custom-image/chroot/boot/vmlinuz* iso/casper/vmlinuz
          sudo cp custom-image/chroot/boot/initrd.img* iso/casper/initrd

      - name: Create grub configuration
        run: |
          cat <<EOF | sudo tee iso/boot/grub/grub.cfg
          set default=0
          set timeout=5

          menuentry "Start Ubuntu MATE 24.04 Live" {
              linux /casper/vmlinuz boot=casper quiet splash ---
              initrd /casper/initrd
          }
          EOF

      - name: Build ISO
        run: |
          grub-mkrescue -o ubuntu-2404-mate-live.iso iso --compress=xz

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-2404-mate-live.iso
          path: ubuntu-2404-mate-live.iso
