name: Build Live ISO (Ubuntu 24.04 CLI)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build Ubuntu 24.04 Live ISO (CLI)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore APT lists cache
        uses: actions/cache@v4
        with:
          path: /var/lib/apt/lists
          key: apt-lists-${{ runner.os }}-${{ hashFiles('**/config/package-lists/**') }}
          restore-keys: |
            apt-lists-${{ runner.os }}-

      - name: Restore APT archive cache
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: apt-archives-${{ runner.os }}-${{ hashFiles('**/config/package-lists/**') }}
          restore-keys: |
            apt-archives-${{ runner.os }}-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y live-build

      - name: Configure Live Build
        run: |
          cd config
          sudo lb config -d noble \
            --binary-images iso-hybrid \
            --bootappend-live "boot=live components username=liveuser hostname=hardclone-live" \
            --memtest none \
            --bootloader grub-efi \
            --syslinux none \
            --debian-installer false

      - name: Build ISO
        run: |
          cd config
          sudo lb build

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-live-cli.iso
          path: config/live-image-amd64.hybrid.iso
