name: Build Ubuntu CLI Live ISO

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install required packages
      run: |
        sudo apt update
        sudo apt install -y debootstrap grub-pc-bin grub-efi-amd64-bin grub-common grub-mkrescue xorriso mtools squashfs-tools

    - name: Create root filesystem
      run: |
        sudo debootstrap --arch=amd64 noble chroot http://archive.ubuntu.com/ubuntu

    - name: Configure system
      run: |
        echo "ubuntu" | sudo tee chroot/etc/hostname
        echo "root:ubuntu" | sudo chroot chroot chpasswd
        echo "ubuntu ALL=(ALL) NOPASSWD: ALL" | sudo tee chroot/etc/sudoers.d/ubuntu
        sudo chroot chroot useradd -m -s /bin/bash ubuntu
        sudo chroot chroot chpasswd <<< "ubuntu:ubuntu"
        sudo chroot chroot apt update
        sudo chroot chroot apt install -y systemd-sysv sudo apparmor bash-completion net-tools curl wget
        sudo chroot chroot apt clean

    - name: Set up AppImage support directory
      run: |
        sudo mkdir -p chroot/opt/appimages
        sudo chown -R root:root chroot/opt

    - name: Compress filesystem
      run: |
        sudo mksquashfs chroot filesystem.squashfs -e boot

    - name: Prepare ISO structure
      run: |
        mkdir -p iso/boot/grub
        sudo cp -vL /boot/vmlinuz* iso/boot/
        sudo cp -vL /boot/initrd.img* iso/boot/
        sudo cp -v /usr/lib/grub/i386-pc/* iso/boot/grub/

    - name: Copy compressed rootfs
      run: |
        sudo mkdir -p iso/live
        sudo cp filesystem.squashfs iso/live/

    - name: Create GRUB configuration
      run: |
        cat <<EOF | sudo tee iso/boot/grub/grub.cfg
        set default=0
        set timeout=5

        menuentry "Ubuntu CLI Live" {
            linux /boot/vmlinuz root=/dev/ram0 ramdisk_size=1500000 ip=dhcp rw quiet
            initrd /boot/initrd.img
        }
        EOF

    - name: Build ISO
      run: |
        grub-mkrescue -o ubuntu-cli-live.iso iso

    - name: Upload ISO artifact
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-cli-live
        path: ubuntu-cli-live.iso
