name: Build Ubuntu 24.04 Live ISO with KDE

on:
  workflow_dispatch:

jobs:
  build-live-iso:
    runs-on: ubuntu-latest
    container: ubuntu:24.04

    steps:
      - name: Install required tools
        run: |
          apt update
          DEBIAN_FRONTEND=noninteractive apt install -y \
            debootstrap \
            xorriso \
            squashfs-tools \
            grub-pc-bin \
            grub-efi-amd64-bin \
            mtools \
            dosfstools \
            isolinux \
            syslinux-utils \
            wget \
            sudo \
            rsync \
            systemd-sysv

      - name: Create working directories
        run: |
          mkdir -p ~/live-build/{chroot,iso}

      - name: Bootstrap Ubuntu 24.04 (noble)
        run: |
          debootstrap --arch=amd64 noble ~/live-build/chroot http://archive.ubuntu.com/ubuntu/

      - name: Configure chroot (KDE + live user)
        run: |
          echo '#!/bin/bash' > ~/live-build/chroot/customize.sh
          echo 'export DEBIAN_FRONTEND=noninteractive' >> ~/live-build/chroot/customize.sh
          echo 'apt update' >> ~/live-build/chroot/customize.sh
          echo 'apt install -y ubuntu-standard casper network-manager sudo kde-plasma-desktop sddm xinit' >> ~/live-build/chroot/customize.sh
          echo 'useradd -m -s /bin/bash liveuser' >> ~/live-build/chroot/customize.sh
          echo 'echo "liveuser:live" | chpasswd' >> ~/live-build/chroot/customize.sh
          echo 'usermod -aG sudo liveuser' >> ~/live-build/chroot/customize.sh
          echo 'mkdir -p /etc/sddm.conf.d' >> ~/live-build/chroot/customize.sh
          echo 'echo "[Autologin]" > /etc/sddm.conf.d/autologin.conf' >> ~/live-build/chroot/customize.sh
          echo 'echo "User=liveuser" >> /etc/sddm.conf.d/autologin.conf' >> ~/live-build/chroot/customize.sh
          echo 'echo "Session=plasma.desktop" >> /etc/sddm.conf.d/autologin.conf' >> ~/live-build/chroot/customize.sh
          echo 'systemctl enable sddm' >> ~/live-build/chroot/customize.sh
          echo 'apt clean' >> ~/live-build/chroot/customize.sh

          chmod +x ~/live-build/chroot/customize.sh
          mount --bind /dev ~/live-build/chroot/dev
          chroot ~/live-build/chroot /customize.sh
          umount ~/live-build/chroot/dev
          rm ~/live-build/chroot/customize.sh

      - name: Prepare ISO structure
        run: |
          mkdir -p ~/live-build/iso/{casper,boot/grub,isolinux}
          cp /usr/lib/ISOLINUX/isolinux.bin ~/live-build/iso/isolinux/
          cp /usr/lib/syslinux/modules/bios/* ~/live-build/iso/isolinux/
          mksquashfs ~/live-build/chroot ~/live-build/iso/casper/filesystem.squashfs -e boot

          echo "ubuntu 24.04 live" > ~/live-build/iso/README.diskdefines
          echo "casper" > ~/live-build/iso/casper/ubuntu.version
          touch ~/live-build/iso/casper/filesystem.manifest
          touch ~/live-build/iso/casper/filesystem.size

      - name: Copy kernel and initrd
        run: |
          cp ~/live-build/chroot/boot/vmlinuz-* ~/live-build/iso/casper/vmlinuz
          cp ~/live-build/chroot/boot/initrd.img-* ~/live-build/iso/casper/initrd

      - name: Generate GRUB config
        run: |
          mkdir -p ~/live-build/iso/boot/grub
          echo "set timeout=5" > ~/live-build/iso/boot/grub/grub.cfg
          echo "menuentry 'Ubuntu 24.04 Live KDE' {" >> ~/live-build/iso/boot/grub/grub.cfg
          echo "    linux /casper/vmlinuz boot=casper quiet splash ---" >> ~/live-build/iso/boot/grub/grub.cfg
          echo "    initrd /casper/initrd" >> ~/live-build/iso/boot/grub/grub.cfg
          echo "}" >> ~/live-build/iso/boot/grub/grub.cfg

      - name: Create the ISO
        run: |
          grub-mkrescue -o ~/ubuntu-24.04-live-kde.iso ~/live-build/iso || \
            echo "Skipping isohybrid - ISO will still be bootable"

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-24.04-live-kde
          path: ~/ubuntu-24.04-live-kde.iso
