name: Build Ubuntu CLI ISO

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-ubuntu-iso:
    runs-on: ubuntu-latest
    name: Build Custom Ubuntu CLI ISO

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y debootstrap squashfs-tools xorriso grub-pc-bin grub-efi-amd64-bin mtools dosfstools

      - name: Bootstrap minimal Ubuntu 24.04 system
        run: |
          sudo debootstrap --arch=amd64 noble chroot http://archive.ubuntu.com/ubuntu/

      - name: Configure system (user, hostname, sudo)
        run: |
          sudo chroot chroot /bin/bash -c "
            echo 'custom-live' > /etc/hostname
            useradd -m -s /bin/bash ubuntu
            echo 'ubuntu:ubuntu' | chpasswd
            usermod -aG sudo ubuntu
            apt update
            apt install -y sudo systemd-sysv net-tools curl vim
            apt clean
          "

      - name: Prepare ISO root directory
        run: |
          mkdir -p iso/{casper,boot/grub}
          sudo mksquashfs chroot iso/casper/filesystem.squashfs -e boot
          echo "ubuntu" | sudo tee iso/casper/hostname
          echo "filesystem.squashfs" | sudo tee iso/casper/filesystem.manifest

          echo "(hd0) /dev/cdrom" > iso/boot/grub/device.map
          grub-mkrescue -o ubuntu-live.iso iso

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-live-cli
          path: ubuntu-live.iso
