name: Build NUMSR Ubuntu Live ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            debootstrap \
            squashfs-tools \
            xorriso \
            grub-pc-bin \
            grub-efi-amd64-bin \
            mtools

      - name: Create working directories
        run: |
          sudo mkdir -p chroot
          sudo mkdir -p chroot/opt/appimages


      - name: Bootstrap Ubuntu base system
        run: |
          sudo debootstrap --arch=amd64 focal chroot http://archive.ubuntu.com/ubuntu/

      - name: Copy AppImages into chroot
        run: |
          sudo cp -rv appimages/*.AppImage chroot/opt/appimages/

      - name: Prepare ISO root filesystem
        run: |
          sudo mksquashfs chroot msr.squashfs -comp xz

      - name: Create ISO directory structure
        run: |
          mkdir -p msr_desktop/boot/grub
          cp msr.squashfs msr_desktop/

      # Secure Boot support disabled for now
      # - name: Generate Secure Boot keys
      #   run: |
      #     mkdir keys
      #     openssl req -new -x509 -newkey rsa:2048 -keyout keys/platform.key -out keys/platform.crt -days 3650 -nodes -subj "/CN=NUMSR/"
      #     openssl x509 -outform DER -in keys/platform.crt -out keys/platform.cer

      # - name: Copy keys to ISO
      #   run: |
      #     cp -rv keys/* msr_desktop/boot/grub/

      - name: Create GRUB configuration
        run: |
          cat > msr_desktop/boot/grub/grub.cfg <<EOF
          insmod all_video
          set timeout=5
          menuentry "NUMSR Ubuntu Live" {
              linux /casper/vmlinuz boot=casper quiet splash ---
              initrd /casper/initrd
          }
          EOF

      - name: Create ISO image
        run: |
          grub-mkrescue -o msr.iso msr_desktop

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: NUMSR-Ubuntu-Live
          path: msr.iso
