name: Build Ubuntu 24.04 Live ISO

on:
  workflow_dispatch:

jobs:
  build-live-iso:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            debootstrap squashfs-tools xorriso grub-pc-bin grub-efi-amd64-bin mtools \
            dosfstools isolinux syslinux-common syslinux-utils

      - name: Create working directories
        run: |
          mkdir -p ~/live-build/{chroot,iso}

      - name: Bootstrap Ubuntu 24.04 LTS
        run: |
          sudo debootstrap --arch=amd64 noble ~/live-build/chroot http://archive.ubuntu.com/ubuntu/

      - name: Configure chroot system
        run: |
          sudo mount --bind /dev ~/live-build/chroot/dev
          sudo cp /etc/resolv.conf ~/live-build/chroot/etc/

          sudo chroot ~/live-build/chroot /bin/bash -c "
            apt-get update
            apt-get install -y ubuntu-standard casper lupin-casper discover laptop-detect os-prober network-manager net-tools \
              locales sudo systemd-sysv plymouth \
              xorg lightdm firefox \
              kde-plasma-desktop
            echo 'live ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/live
            useradd -m -s /bin/bash live
            passwd -d live
            locale-gen en_US.UTF-8
            echo 'ubuntu-live' > /etc/hostname
            echo 'LANG=en_US.UTF-8' > /etc/default/locale
          "

          sudo umount ~/live-build/chroot/dev

      - name: Create squashfs
        run: |
          sudo mksquashfs ~/live-build/chroot ~/live-build/iso/casper/filesystem.squashfs -e boot

      - name: Copy kernel and initrd
        run: |
          sudo cp ~/live-build/chroot/boot/vmlinuz* ~/live-build/iso/casper/vmlinuz
          sudo cp ~/live-build/chroot/boot/initrd.img* ~/live-build/iso/casper/initrd

      - name: Write grub config
        run: |
          mkdir -p ~/live-build/iso/boot/grub
          cat <<EOF > ~/live-build/iso/boot/grub/grub.cfg
          set timeout=10
          menuentry "Try Ubuntu 24.04 Live (KDE)" {
              linux /casper/vmlinuz boot=casper quiet splash ---
              initrd /casper/initrd
          }
EOF

      - name: Create the ISO
        run: |
          grub-mkrescue -o ubuntu-24.04-live.iso ~/live-build/iso || \
            echo "Skipping isohybrid - ISO will still be bootable"

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-24.04-live
          path: ubuntu-24.04-live.iso
