name: Build Ubuntu 24.04 Live ISO

on:
  workflow_dispatch:

jobs:
  build-live-iso:
    runs-on: ubuntu-latest
    container: ubuntu:24.04

    steps:
      - name: Install required tools
        run: |
          apt update
          DEBIAN_FRONTEND=noninteractive apt install -y \
            debootstrap \
            xorriso \
            squashfs-tools \
            grub-pc-bin \
            grub-efi-amd64-bin \
            mtools \
            dosfstools \
            isolinux \
            syslinux-utils \
            wget \
            sudo \
            rsync

      - name: Create working directories
        run: |
          mkdir -p ~/live-build/{chroot,iso}

      - name: Bootstrap minimal Ubuntu system
        run: |
          debootstrap --arch=amd64 noble ~/live-build/chroot http://archive.ubuntu.com/ubuntu/

      - name: Customize chroot (install apps, etc.)
        run: |
          echo '#!/bin/bash
          apt update
          apt install -y ubuntu-standard casper network-manager
          apt clean
          ' > ~/live-build/chroot/customize.sh
          chmod +x ~/live-build/chroot/customize.sh
          chroot ~/live-build/chroot /customize.sh
          rm ~/live-build/chroot/customize.sh

      - name: Prepare ISO structure
        run: |
          mkdir -p ~/live-build/iso/{casper,boot/grub}
          cp /usr/lib/ISOLINUX/isolinux.bin ~/live-build/iso/isolinux/
          cp /usr/lib/syslinux/modules/bios/* ~/live-build/iso/isolinux/

          mksquashfs ~/live-build/chroot ~/live-build/iso/casper/filesystem.squashfs -e boot

          echo "ubuntu 24.04 live" > ~/live-build/iso/README.diskdefines
          echo "casper" > ~/live-build/iso/casper/ubuntu.version

          touch ~/live-build/iso/casper/filesystem.manifest
          touch ~/live-build/iso/casper/filesystem.size

      - name: Generate grub config
        run: |
          cat > ~/live-build/iso/boot/grub/grub.cfg <<EOF
          set timeout=5
          menuentry "Ubuntu 24.04 Live" {
              linux /casper/vmlinuz boot=casper quiet splash ---
              initrd /casper/initrd
          }
          EOF

      - name: Copy kernel and initrd
        run: |
          cp ~/live-build/chroot/boot/vmlinuz-* ~/live-build/iso/casper/vmlinuz
          cp ~/live-build/chroot/boot/initrd.img-* ~/live-build/iso/casper/initrd

      - name: Create the ISO
        run: |
          grub-mkrescue -o ~/ubuntu-24.04-live.iso ~/live-build/iso

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-24.04-live
          path: ~/ubuntu-24.04-live.iso
