name: Build Ubuntu CLI Live ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y debootstrap xorriso isolinux squashfs-tools grub-pc-bin grub-efi-amd64-bin mtools

      - name: Create root filesystem
        run: |
          sudo debootstrap --arch=amd64 noble chroot http://archive.ubuntu.com/ubuntu

      - name: Configure chroot
        run: |
          sudo mount --bind /dev chroot/dev
          sudo mount --bind /proc chroot/proc
          sudo mount --bind /sys chroot/sys

          sudo chroot chroot /bin/bash -c "
            export DEBIAN_FRONTEND=noninteractive

            apt update
            apt install -y linux-image-generic initramfs-tools systemd-sysv sudo apparmor apparmor-utils

            useradd -m -s /bin/bash ubuntu
            echo 'ubuntu:ubuntu' | chpasswd
            usermod -aG sudo ubuntu
            echo 'ubuntu ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/ubuntu

            update-initramfs -c -k all

            apt clean
          "

          sudo umount chroot/dev
          sudo umount chroot/proc
          sudo umount chroot/sys

      - name: Create ISO directories
        run: |
          mkdir -p iso/{boot/grub,boot/isolinux,live}
          mkdir -p chroot/tmp/initrd

      - name: Copy kernel and initrd
        run: |
          sudo cp chroot/boot/vmlinuz-* iso/boot/vmlinuz
          sudo cp chroot/boot/initrd.img-* iso/boot/initrd

      - name: Create squashfs
        run: |
          sudo mksquashfs chroot iso/live/filesystem.squashfs -e boot

      - name: Create grub.cfg
        run: |
          cat <<EOF > iso/boot/grub/grub.cfg
          set default=0
          set timeout=5

          menuentry "Ubuntu CLI Live" {
              linux /boot/vmlinuz boot=live quiet
              initrd /boot/initrd
          }
          EOF

      - name: Create ISO image
        run: |
          grub-mkrescue -o ubuntu-cli-live.iso iso

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-cli-live
          path: ubuntu-cli-live.iso
