name: Build Ubuntu Noble CLI Live ISO

on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y debootstrap grub-pc-bin grub-efi xorriso mtools

      - name: Bootstrap minimal Ubuntu system
        run: |
          sudo debootstrap --arch=amd64 noble chroot-dir http://archive.ubuntu.com/ubuntu/

      - name: Configure system
        run: |
          sudo cp /etc/resolv.conf chroot-dir/etc/
          sudo chroot chroot-dir /bin/bash -c "
            apt-get update
            apt-get install -y linux-image-generic grub-pc-bin grub-efi-amd64-bin sudo systemd-sysv vim
            echo 'ubuntu-live' > /etc/hostname
            useradd -m -s /bin/bash liveuser
            passwd -d liveuser
            echo 'liveuser ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
            echo 'tty1' > /etc/securetty
            mkdir -p /etc/systemd/system/getty@tty1.service.d
            echo '[Service]' > /etc/systemd/system/getty@tty1.service.d/override.conf
            echo 'ExecStart=' >> /etc/systemd/system/getty@tty1.service.d/override.conf
            echo 'ExecStart=-/sbin/agetty --autologin liveuser --noclear %I \$TERM' >> /etc/systemd/system/getty@tty1.service.d/override.conf
          "

      - name: Prepare ISO directory structure
        run: |
          mkdir -p live-iso/iso/{boot/grub,casper}
          sudo cp chroot-dir/boot/vmlinuz* live-iso/iso/casper/vmlinuz
          sudo cp chroot-dir/boot/initrd.img* live-iso/iso/casper/initrd

      - name: Create grub.cfg
        run: |
          cat <<EOF > live-iso/iso/boot/grub/grub.cfg
          set default=0
          set timeout=5

          menuentry "Ubuntu Noble CLI Live" {
              linux /casper/vmlinuz boot=live quiet
              initrd /casper/initrd
          }
          EOF

      - name: Build ISO
        run: |
          grub-mkrescue -o ubuntu-noble-cli-live.iso live-iso/iso --compress=xz

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-noble-cli-live
          path: ubuntu-noble-cli-live.iso
