name: Build Ubuntu CLI Live ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            debootstrap xorriso grub-pc-bin grub-efi-amd64-bin mtools squashfs-tools dosfstools

      - name: Create directory structure
        run: |
          mkdir -p live-iso/{chroot,iso/boot/grub}

      - name: Bootstrap Ubuntu CLI into chroot
        run: |
          sudo debootstrap --variant=minbase focal live-iso/chroot http://archive.ubuntu.com/ubuntu/

      - name: Set up basic system configuration
        run: |
          echo "ubuntu-cli-live" | sudo tee live-iso/chroot/etc/hostname
          sudo chroot live-iso/chroot apt-get update
          sudo chroot live-iso/chroot apt-get install -y linux-image-generic grub-pc systemd-sysv sudo vim net-tools network-manager

      - name: Create a default user with sudo
        run: |
          echo "liveuser:x:1000:1000:Live User,,,:/home/liveuser:/bin/bash" | sudo tee -a live-iso/chroot/etc/passwd
          echo "liveuser:x:1000:" | sudo tee -a live-iso/chroot/etc/group
          sudo mkdir -p live-iso/chroot/home/liveuser
          echo 'liveuser ALL=(ALL) NOPASSWD:ALL' | sudo tee live-iso/chroot/etc/sudoers.d/liveuser
          sudo chroot live-iso/chroot chown -R 1000:1000 /home/liveuser

      - name: Clean up chroot
        run: |
          sudo chroot live-iso/chroot apt-get clean
          sudo rm -rf live-iso/chroot/var/lib/apt/lists/*

      - name: Create SquashFS filesystem
        run: |
          sudo mksquashfs live-iso/chroot live-iso/iso/filesystem.squashfs -e boot

      - name: Copy kernel and initrd
        run: |
          mkdir -p live-iso/iso/boot
          sudo cp "$(readlink -f /boot/vmlinuz)" live-iso/iso/boot/vmlinuz
          sudo cp "$(readlink -f /boot/initrd.img)" live-iso/iso/boot/initrd
          sudo chown -R $USER:$USER live-iso/iso/boot
          chmod -R a+r live-iso/iso/boot


      - name: Create grub config
        run: |
          sudo mkdir -p live-iso/iso/boot/grub
          echo 'set default=0' | sudo tee live-iso/iso/boot/grub/grub.cfg
          echo 'set timeout=5' | sudo tee -a live-iso/iso/boot/grub/grub.cfg
          echo '' | sudo tee -a live-iso/iso/boot/grub/grub.cfg
          echo 'menuentry "Ubuntu CLI Live" {' | sudo tee -a live-iso/iso/boot/grub/grub.cfg
          echo '    linux /boot/vmlinuz boot=live quiet' | sudo tee -a live-iso/iso/boot/grub/grub.cfg
          echo '    initrd /boot/initrd' | sudo tee -a live-iso/iso/boot/grub/grub.cfg
          echo '}' | sudo tee -a live-iso/iso/boot/grub/grub.cfg

      - name: Build ISO image
        run: |
          grub-mkrescue -o ubuntu-cli-live.iso live-iso/iso --compress=xz

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-cli-live
          path: ubuntu-cli-live.iso
