name: Build Ubuntu Noble CLI Live ISO

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y debootstrap squashfs-tools grub-pc-bin grub-efi-amd64-bin xorriso

      - name: Create root filesystem with debootstrap
        run: |
          sudo debootstrap --arch=amd64 noble chroot-dir http://archive.ubuntu.com/ubuntu/

      - name: Install kernel and casper in chroot
        run: |
          sudo chroot chroot-dir apt-get update
          sudo chroot chroot-dir apt-get install -y linux-generic casper

      - name: Copy kernel and initrd from chroot
        run: |
          mkdir -p live-iso/iso/boot
          cp chroot-dir/boot/vmlinuz-* live-iso/iso/boot/vmlinuz
          cp chroot-dir/boot/initrd.img-* live-iso/iso/boot/initrd

      - name: Create squashfs filesystem
        run: |
          sudo mksquashfs chroot-dir live-iso/iso/casper/filesystem.squashfs -e boot

      - name: Create grub config
        run: |
          mkdir -p live-iso/iso/boot/grub
          echo "set default=0" > live-iso/iso/boot/grub/grub.cfg
          echo "set timeout=5" >> live-iso/iso/boot/grub/grub.cfg
          echo "" >> live-iso/iso/boot/grub/grub.cfg
          echo 'menuentry "Ubuntu CLI Live" {' >> live-iso/iso/boot/grub/grub.cfg
          echo '    linux /boot/vmlinuz boot=casper quiet ---' >> live-iso/iso/boot/grub/grub.cfg
          echo '    initrd /boot/initrd' >> live-iso/iso/boot/grub/grub.cfg
          echo '}' >> live-iso/iso/boot/grub/grub.cfg

      - name: Create ISO image
        run: |
          grub-mkrescue -o ubuntu-noble-cli-live-iso.iso live-iso/iso --compress=xz

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-noble-cli-live-iso
          path: ubuntu-noble-cli-live-iso.iso
