name: Build Ubuntu Noble CLI Live ISO

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y debootstrap xorriso squashfs-tools grub-pc-bin grub-efi-amd64-bin mtools

      - name: Bootstrap Ubuntu Noble
        run: |
          sudo debootstrap --variant=minbase noble chroot-dir http://archive.ubuntu.com/ubuntu/

      - name: Configure chroot environment
        run: |
          sudo cp /etc/resolv.conf chroot-dir/etc/
          sudo mount --bind /dev chroot-dir/dev
          sudo mount --bind /dev/pts chroot-dir/dev/pts
          sudo mount -t proc /proc chroot-dir/proc
          sudo mount -t sysfs /sys chroot-dir/sys
          sudo chroot chroot-dir /bin/bash -c "
            apt-get update &&
            apt-get install -y linux-image-generic casper sudo &&
            useradd -m -s /bin/bash liveuser &&
            echo 'liveuser ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
          "
          sudo umount -lf chroot-dir/dev/pts
          sudo umount -lf chroot-dir/dev
          sudo umount -lf chroot-dir/proc
          sudo umount -lf chroot-dir/sys

      - name: Create ISO directory structure
        run: |
          mkdir -p live-iso/iso/casper
          mkdir -p live-iso/iso/boot/grub

      - name: Create squashfs
        run: |
          sudo mksquashfs chroot-dir live-iso/iso/casper/filesystem.squashfs -e boot

      - name: Copy kernel and initrd
        run: |
          KERNEL=$(ls chroot-dir/boot/vmlinuz-* | head -n1 | xargs -n1 basename)
          INITRD=$(ls chroot-dir/boot/initrd.img-* | head -n1 | xargs -n1 basename)

          sudo cp chroot-dir/boot/$KERNEL live-iso/iso/casper/vmlinuz
          sudo cp chroot-dir/boot/$INITRD live-iso/iso/casper/initrd

      - name: Create grub.cfg
        run: |
          cat <<EOF > live-iso/iso/boot/grub/grub.cfg
          set default=0
          set timeout=5

          menuentry "Ubuntu Noble CLI Live" {
              linux /casper/vmlinuz boot=casper quiet ---
              initrd /casper/initrd
          }
          EOF

      - name: Build ISO
        run: |
          grub-mkrescue -o ubuntu-noble-cli-live-iso.iso live-iso/iso --compress=xz

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-noble-cli-live-iso
          path: ubuntu-noble-cli-live-iso.iso
